version: 2.1
orbs:
  # Your orb will be automatically injected here during the pipeline.
  # Reference your orb's jobs and commands below as they will exist when built.
  orb-tools: circleci/orb-tools@12.0
  # The orb definition is intentionally not included here. It will be injected into the pipeline.
  circleback: {}

parameters:
  test:
    type: string
    default: ""
    description: "Whether this is test pipeline."
  circleback_workflow_id:
    type: string
    default: ""
    description: "The parameter that contains the CircleCI workflow ID."

workflows:
  approve_test_job:
    jobs:
      - circleback/approve:
          project: github/justindalton/circleback-orb
          workflow_id: << pipeline.parameters.circleback_workflow_id >>
          approval_job: approval-test
